# Generated by Django 4.2.20 on 2026-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('', 'Select budget range'), ('below_25k', 'Below 25,000/month'), ('25k_50k', '25,000 - 50,000/month'), ('50k_1l', '50,000 - 1,00,000/month'), ('above_1l', 'Above 1,00,000/month'), ('discuss', 'Prefer to discuss')], max_length=30),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='service_interested',
            field=models.CharField(blank=True, choices=[('', 'Select a service'), ('virtual_cfo', 'Virtual CFO Services'), ('tax_planning', 'Tax Planning & Compliance'), ('business_advisory', 'Business Advisory'), ('accounting', 'Accounting & Bookkeeping'), ('audit', 'Audit & Assurance'), ('gst', 'GST Compliance'), ('company_formation', 'Company Formation'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='urgency',
            field=models.CharField(blank=True, choices=[('', 'Select timeline'), ('immediate', 'Immediate (Within a week)'), ('short', 'Short-term (1-2 months)'), ('medium', 'Medium-term (3-6 months)'), ('flexible', 'Flexible / No rush')], max_length=20),
        ),
    ]
